apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-suivi-budg
  labels:
    app: suivi-budg
spec:
  replicas: 2
  selector:
    matchLabels:
      app: suivi-budg
  template:
    metadata:
      labels:
        app: suivi-budg
    spec:
      containers:
      - name: suivi-budg
        image: julo1997/suivi-budgetaire
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: suivi-budg-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: APP_KEY
          value: base64:tbU4fDykbiioPH8ZTrOtO76a9efu3NBJPMTxmgZ/9V8=
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        volumeMounts:
        - name: storage
          mountPath: /var/www/html/storage
      volumes:
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: suivi-budg-service
spec:
  selector:
    app: suivi-budg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
