apiVersion: apps/v1
kind: Deployment
metadata:
  name: suivi-budg-db
  labels:
    app: suivi-budg-db
spec:
  selector:
    matchLabels:
      app: suivi-budg-db
  template:
    metadata:
      labels:
        app: suivi-budg-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: suivi_budgetaire
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: suivi-budg-db-service
spec:
  selector:
    app: suivi-budg-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP