# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: suivi-budgetaire
spec:
  type: NodePort
  selector:
    app: app-suivbudg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
