apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: suivi-depense-budg
  name: suivi-depense-budg
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: suivi-depense-budg
  type: NodePort
status:
  loadBalancer: {}
